SELECT * FROM CORDER;

SELECT * FROM CUSTOMER_SEND;

CREATE TABLE PRICE_RATIO (
	SERVICE_CUSTOMER VARCHAR(8) PRIMARY KEY,
	RATIO REAL
)

INSERT INTO PRICE_RATIO (SERVICE_CUSTOMER,RATIO) VALUES
	('NORMAL',1.0),
	('DISCOUNT',0.8),
	('EXPRESS',1.1)

CREATE TABLE KILOMETER_DISTANCE (
	PROVINCE VARCHAR(32) PRIMARY KEY,
	DISTANCE INT
)

INSERT INTO KILOMETER_DISTANCE (PROVINCE,DISTANCE) VALUES
	('HA NOI',0),
	('HO CHI MINH',1710),
	('HUE',658),
	('DA NANG',763),
	('BAC NINH',31),
	('AN GIANG',1900),
	('DA LAT',1481),
	('THANH HOA',153),
	('QUANG TRI',889),
	('PHU THO',93),
	('NHA TRANG',1278),
	('CAN THO',1877),
	('LAO CAI',338);

SELECT * FROM CORDER

--tinh toan tong so tien gui cua nguoi gui
--tham so dau vao: @ssn nguoi gui -> tra ra tong so tien nguoi do phai tra tu cac hoa don

DROP TABLE IF EXISTS ORDER_ASC
SELECT TOP 20 * INTO ORDER_ASC FROM CORDER ORDER BY O_IDX
	
CREATE FUNCTION COST_FOR_CUSTOMER_SEND(
	@ssn VARCHAR(10)
)
RETURNS REAL
AS
BEGIN
	--CHECK SSN
	IF LEN(@ssn) <> 9 OR @ssn NOT LIKE '[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]'
		RETURN -1.0
	ELSE IF @ssn NOT IN (SELECT SSN FROM PERSON) 
		RETURN -1.0
	--QUERY
	--1-N CUSTOMER SEND -> RETRIEVE SERVICE_RATIO;
	DECLARE @ratio REAL
	SET @ratio = (SELECT TEMP.RATIO FROM
					(SELECT CUSTOMER_SEND.SSN, PRICE_RATIO.RATIO
					FROM CUSTOMER_SEND
					JOIN PRICE_RATIO ON CUSTOMER_SEND.SERVICE = PRICE_RATIO.SERVICE_CUSTOMER) 
				AS TEMP WHERE TEMP.SSN = @ssn)
	RETURN @ratio
	--1-N CUSTOMER RECEIVE -> RETRIVE ADDRESS_RECEIVE;

	--1-N PACKAGE -> RETRIEVE ADDRESS_SEND;


END;



SELECT * FROM ORDER_ASC

SELECT dbo.COST_FOR_CUSTOMER_SEND('182835988')

