SELECT * FROM CORDER;

SELECT * FROM CUSTOMER_SEND;

CREATE TABLE PRICE_RATIO (
	SERVICE_CUSTOMER	VARCHAR(8) PRIMARY KEY,
	RATIO REAL
)

INSERT INTO PRICE_RATIO (SERVICE_CUSTOMER,RATIO) VALUES
	('NORMAL',1.0),
	('DISCOUNT',0.8),
	('EXPRESS',1.1)

CREATE TABLE KILOMETER_DISTANCE (
	PROVINCE VARCHAR(32) PRIMARY KEY,
	DISTANCE INT
)

INSERT INTO KILOMETER_DISTANCE (PROVINCE,DISTANCE) VALUES
	('HA NOI',0),
	('HO CHI MINH',1710),
	('HUE',658),
	('DA NANG',763),
	('BAC NINH',31),
	('AN GIANG',1900),
	('DA LAT',1481),
	('THANH HOA',153),
	('QUANG TRI',889),
	('PHU THO',93),
	('NHA TRANG',1278),
	('CAN THO',1877),
	('LAO CAI',338);_