--USE master;

DROP TABLE IF EXISTS ALTERNATIVE_RECEIVER
DROP TABLE IF EXISTS ALTERNATIVE_RECEIVE_PHONE
DROP TABLE IF EXISTS PACKAGE
DROP TABLE IF EXISTS CORDER
DROP TABLE IF EXISTS CUSTOMER_RECEIVE
DROP TABLE IF EXISTS CUSTOMER_SEND
DROP TABLE IF EXISTS DRIVES
DROP TABLE IF EXISTS DRIVER
DROP TABLE IF EXISTS EMPLOYEE
DROP TABLE IF EXISTS PERSON_MAIL
DROP TABLE IF EXISTS PERSON_PHONE
DROP TABLE IF EXISTS VEHICLE
DROP TABLE IF EXISTS ACCOUNT
DROP TABLE IF EXISTS PERSON
