USE DRIVER_SERVICE

--EMPLOYEE ACCOUNT
INSERT INTO ACCOUNT(ATYPE,UNAME,PASS,ID,SSN) VALUES ();
INSERT INTO ACCOUNT(ATYPE,UNAME,PASS,ID,SSN) VALUES ();
INSERT INTO ACCOUNT(ATYPE,UNAME,PASS,ID,SSN) VALUES ();
INSERT INTO ACCOUNT(ATYPE,UNAME,PASS,ID,SSN) VALUES ();
INSERT INTO ACCOUNT(ATYPE,UNAME,PASS,ID,SSN) VALUES ();
INSERT INTO ACCOUNT(ATYPE,UNAME,PASS,ID,SSN) VALUES ();
INSERT INTO ACCOUNT(ATYPE,UNAME,PASS,ID,SSN) VALUES ();
INSERT INTO ACCOUNT(ATYPE,UNAME,PASS,ID,SSN) VALUES ();
INSERT INTO ACCOUNT(ATYPE,UNAME,PASS,ID,SSN) VALUES ();
INSERT INTO ACCOUNT(ATYPE,UNAME,PASS,ID,SSN) VALUES ();

--CUSTOMER_ACCOUNT