USE DRIVER_SERVICE;

CREATE TABLE PERSON (
    SSN NUMERIC(9) NOT NULL PRIMARY KEY,
    First_name  VARCHAR NOT NULL,
    Last_name   VARCHAR NOT NULL,
    Gender      VARCHAR
);

CREATE TABLE CUSTOMER_RECEIVE (
    SSN NUMERIC(9) NOT NULL PRIMARY KEY REFERENCES PERSON(SSN),
    ADDR    VARCHAR NOT NULL
);

    DROP TABLE IF EXISTS CUSTOMER_SEND;
    CREATE TABLE CUSTOMER_SEND (
        SSN     NUMERIC(9) NOT NULL REFERENCES PERSON(SSN),
        SERV    VARCHAR NOT NULL, 
        PRIMARY KEY (SSN)
    );

   CREATE TABLE EMPLOYEE (
        SSN     NUMERIC(9) NOT NULL PRIMARY KEY REFERENCES PERSON(SSN),
        E_ID    NUMERIC(7) NOT NULL,
        DATE_BEGIN  DATE NOT NULL,
        EXP     TINYINT,
        SUPSSN  NUMERIC(9) NOT NULL,
      	FOREIGN KEY (SUPSSN) REFERENCES EMPLOYEE(SSN)
    );

  CREATE TABLE VEHICLE(
        VNUM    VARCHAR(10) NOT NULL PRIMARY KEY,
        RNUM    VARCHAR(9),
        VTYPE   VARCHAR
    );

   CREATE TABLE DRIVER(
        SSN     NUMERIC(9) NOT NULL REFERENCES PERSON(SSN),
        LICENSE_ID VARCHAR(9) NOT NULL,
        EXP TINYINT,
        PRIMARY KEY (SSN)
    );

   CREATE TABLE DRIVES(
        SSN NUMERIC(9) NOT NULL REFERENCES DRIVER(SSN),
        VNUM VARCHAR(10) NOT NULL REFERENCES VEHICLE(VNUM),
        PRIMARY KEY (SSN, VNUM)
    );

    CREATE TABLE PERSON_MAIL(
        SSN NUMERIC(9) NOT NULL REFERENCES PERSON(SSN),
        MAIL    VARCHAR,
        PRIMARY KEY (SSN,MAIL)
    );

   CREATE TABLE PERSON_PHONE(
        SSN     NUMERIC(9) NOT NULL REFERENCES PERSON(SSN),
        PHONE   NUMERIC(10),
        PRIMARY KEY (SSN,PHONE)
    );  


   CREATE TABLE ALTERNATIVE_RECEIVER(
        SSN NUMERIC(9) NOT NULL REFERENCES CUSTOMER_RECEIVE(SSN),
        FNAME VARCHAR NOT NULL,
      	PHONE 	NUMERIC(10),
        RELATIONSHIP    VARCHAR,
      	PRIMARY KEY (SSN,FNAME,PHONE)
    );


    CREATE TABLE ALTERNATIVE_RECEIVE_PHONE(
        SSN     NUMERIC(9) NOT NULL,
        FNAME   VARCHAR NOT NULL,   
        PHONE   NUMERIC(10),
      FOREIGN KEY (SSN,FNAME,PHONE) REFERENCES ALTERNATIVE_RECEIVER(SSN,FNAME,PHONE)
    );

    CREATE TABLE ACCOUNT(
        ID      NUMERIC(9) NOT NULL PRIMARY KEY,
        ATYPE   VARCHAR,
        UNAME   VARCHAR,
        PASS    VARCHAR,
        SSN     NUMERIC(9) NOT NULL REFERENCES PERSON(SSN)
    );

   CREATE TABLE CORDER(
        SSN_CR      NUMERIC(9) NOT NULL REFERENCES CUSTOMER_RECEIVE(SSN),
        SSN_CS      NUMERIC(9) NOT NULL REFERENCES CUSTOMER_SEND(SSN),
        SSN_EMP     NUMERIC(9) NOT NULL REFERENCES EMPLOYEE(SSN),
        ORDERID 	NUMERIC(9) NOT NULL,
        ADD_SEND    VARCHAR,
        ADD_RECEIVE VARCHAR,
        TWEIGHT     FLOAT(3),
        NOPACKAGE   SMALLINT,
        TPRICE      MONEY,
        RATE        TINYINT,
        PTYPE       VARCHAR,
        OTIME       DATETIME,
        PRIMARY KEY (ORDERID)
    );

   CREATE TABLE PACKAGE(
        PID NUMERIC(9) NOT NULL,
        NUM     TINYINT,
        PWEIGHT FLOAT(3),
        TNAME   VARCHAR,
        ORDERID NUMERIC(9) NOT NULL REFERENCES CORDER(ORDERID),
        SSN     NUMERIC(9) NOT NULL REFERENCES DRIVER(SSN),
        CTIME   DATETIME,
        DTIME   DATETIME,
        WLOCATION   VARCHAR,
        CLOCATION   VARCHAR,
        PRIMARY KEY (PID,SSN)
    );