CREATE TRIGGER trigger_deleteOrder ON CORDER AFTER DELETE AS
BEGIN
	--update index for corder
	DROP TABLE IF EXISTS CORDER_TEMP
	DROP TABLE IF EXISTS PACKAGE_TEMP
	SELECT * INTO CORDER_TEMP FROM CORDER
	SELECT * INTO PACKAGE_TEMP FROM PACKAGE
	DELETE FROM CORDER;
	DELETE FROM PACKAGE;


	DBCC CHECKIDENT ('CORDER', RESEED, 0)
	INSERT INTO CORDER(SSN_CR,SSN_CS,SSN_EMP,ORDERID,RATE,PaymentType, STATUS, OTIME) SELECT SSN_CR,SSN_CS,SSN_EMP,ORDERID,RATE,PaymentType, STATUS, OTIME FROM CORDER_TEMP;

	DBCC CHECKIDENT ('PACKAGE', RESEED, 0)
	INSERT INTO PACKAGE(PID,PWEIGHT,TypeName,TypeLevel,ORDERID,SSN,TIME,LOCATION) SELECT PID,PWEIGHT,TypeName,TypeLevel,ORDERID,SSN,TIME,LOCATION FROM PACKAGE_TEMP;

	DROP TABLE IF EXISTS CORDER_TEMP
	DROP TABLE IF EXISTS PACKAGE_TEMP
END;