--get number package from every order
--get total weight from every order
/*ALTER PROC LIST_ABOUT_ORDER 
@ssn VARCHAR(10)
AS
BEGIN
	SELECT TEMP.SSN_CS AS SSN,TEMP.ORDERID,COUNT(PACKAGE.PID) AS nPACKAGE,SUM(PACKAGE.PWEIGHT) AS tWEIGHT 
	FROM 
		((SELECT * FROM CORDER WHERE SSN_CS = @ssn) AS TEMP
		JOIN PACKAGE ON TEMP.ORDERID = PACKAGE.ORDERID)
	GROUP BY TEMP.SSN_CS ,TEMP.ORDERID
	HAVING COUNT(PACKAGE.PID) >= 2
	ORDER BY TEMP.ORDERID
END

EXEC LIST_ABOUT_ORDER @ssn = '351524229'
*/

--get number supervisee by supervisor

SELECT * FROM PACKAGE
SELECT * FROM CORDER
SELECT * FROM CUSTOMER_SEND
go
--thủ tục 1 done--
--service có bao nhiêu đơn hàng và mỗi đơn hàng có bao nhiêu package và khối lượng
--lưu ý mỗi thủ tục hàm phải đủ hai loại truy vấn

create or ALTER PROC LIST_ABOUT_SERVICE 
@service VARCHAR(8)
AS
BEGIN
	DROP TABLE IF EXISTS LINKAGE
	SELECT * INTO LINKAGE FROM (CUSTOMER_SEND JOIN CORDER ON CUSTOMER_SEND.SSN = CORDER.SSN_CS);

	SELECT TEMP.SSN_CS AS SSN,TEMP.ORDERID,COUNT(PACKAGE.PID) AS nPACKAGE,SUM(PACKAGE.PWEIGHT) AS tWEIGHT 
	FROM 
		((SELECT * FROM LINKAGE WHERE LINKAGE.SERVICE = @service) AS TEMP
		JOIN PACKAGE ON TEMP.ORDERID = PACKAGE.ORDERID)
	GROUP BY TEMP.SSN_CS ,TEMP.ORDERID
	HAVING COUNT(PACKAGE.PID) >= 2
	ORDER BY TEMP.ORDERID
END
go

EXEC LIST_ABOUT_SERVICE 'NORMAL'
go
-- thủ tục 2 done --
-- hiển thị tất cả tài khoản thuộc loại @type trong (DRIVER, EMPLOYEE, CUSTOMER)
-- với số lượng sđt đăng ký @num_phone
-- khác với ý tưởng ban đầu sử dụng gender ở person nha

CREATE or alter PROC NUMPHONE_ACCOUNT 
@type VARCHAR(8), @num_phone TINYINT
AS
BEGIN
	--DROP TABLE IF EXISTS ACC_PER;
	--SELECT ACCOUNT.SSN, ID, ATYPE, UserName, PASS, PERSON.Gender INTO ACC_PER 
	--FROM ACCOUNT, PERSON 
	--WHERE ACCOUNT.SSN = PERSON.SSN AND ATYPE = @type
	--ORDER BY ID;

	DROP TABLE IF EXISTS ACC_PHONE;
	SELECT ID, COUNT(PHONE) AS NUM_PHONE INTO ACC_PHONE FROM ACCOUNT, PERSON_PHONE
	WHERE ACCOUNT.SSN = PERSON_PHONE.SSN AND ACCOUNT.ATYPE = @type
	GROUP BY ID
	HAVING COUNT(PHONE) = @num_phone
	ORDER BY ID;

	--SELECT * FROM ACC_PHONE;

	SELECT ACCOUNT.ID, UserName, SSN, ATYPE, NUM_PHONE FROM ACC_PHONE, ACCOUNT
	WHERE ACC_PHONE.ID = ACCOUNT.ID
	ORDER BY ACCOUNT.ID;
END
GO

EXEC NUMPHONE_ACCOUNT  'CUSTOMER', 2;