USE DRIVER_SERVICE;

CREATE TABLE PERSON (
    SSN		   CHAR(9) PRIMARY KEY,
    FirstName  TEXT NOT NULL,
    LastName   TEXT NOT NULL,
    Gender     CHAR NOT NULL
);

CREATE TABLE CUSTOMER_RECEIVE (
    SSN CHAR(9) PRIMARY KEY REFERENCES PERSON(SSN),
		--ON DELETE CASCADE
		--ON UPDATE CASCADE,
    ADDRESS   VARCHAR(64) NOT NULL
);

CREATE TABLE CUSTOMER_SEND (
    SSN     CHAR(9) NOT NULL REFERENCES PERSON(SSN),
		--ON DELETE CASCADE
		--ON UPDATE CASCADE,
    SERVICE    VARCHAR(8) NOT NULL, 
    PRIMARY KEY (SSN)
);

CREATE TABLE EMPLOYEE (
	E_IDX		INT NOT NULL IDENTITY(1,1),
    SSN     CHAR(9) PRIMARY KEY REFERENCES PERSON(SSN),
		--ON DELETE CASCADE
		--ON UPDATE CASCADE,
    EID    CHAR(7) NOT NULL UNIQUE,
    DateBegin  DATE NOT NULL,
    EXP     TINYINT,
    SuperSSN  CHAR(9) REFERENCES EMPLOYEE(SSN),
		--ON DELETE SET NULL
		--ON UPDATE CASCADE
	SALARY	BIGINT DEFAULT 0,
	CONSTRAINT 	fk_emp_superssn	FOREIGN KEY (SuperSSN) 
				REFERENCES EMPLOYEE(SSN) 
				ON DELETE NO ACTION
				ON UPDATE NO ACTION,
);

CREATE TABLE VEHICLE (
    VNUM    CHAR(10) PRIMARY KEY,
    RNUM    CHAR(8) NOT NULL UNIQUE,
    VTYPE   TEXT
);

CREATE TABLE DRIVER (
    SSN     CHAR(9) NOT NULL REFERENCES PERSON(SSN)
		ON DELETE CASCADE
		ON UPDATE CASCADE,
    LICENSE_ID CHAR(9) NOT NULL,
    EXP TINYINT,
    PRIMARY KEY (SSN)
);

CREATE TABLE DRIVES (
    SSN CHAR(9) NOT NULL REFERENCES DRIVER(SSN)
		ON DELETE CASCADE
		ON UPDATE CASCADE,
    VNUM CHAR(10) NOT NULL REFERENCES VEHICLE(VNUM)
		ON DELETE CASCADE
		ON UPDATE CASCADE,
    PRIMARY KEY (SSN, VNUM)
);

CREATE TABLE PERSON_MAIL (
    SSN CHAR(9) NOT NULL REFERENCES PERSON(SSN)
		ON DELETE CASCADE
		ON UPDATE CASCADE,
    MAIL    VARCHAR(32) UNIQUE,
    PRIMARY KEY (SSN,MAIL)
);

CREATE TABLE PERSON_PHONE (
    SSN     CHAR(9) NOT NULL REFERENCES PERSON(SSN)
		ON DELETE CASCADE
		ON UPDATE CASCADE,
    PHONE   CHAR(10) UNIQUE,
    PRIMARY KEY (SSN,PHONE)
);  

	
CREATE TABLE ALTERNATIVE_RECEIVER (
    SSN CHAR(9) NOT NULL REFERENCES CUSTOMER_RECEIVE(SSN)
		ON DELETE CASCADE
		ON UPDATE CASCADE,
    FNAME VARCHAR(15) NOT NULL,
  	PHONE 	CHAR(10),
    RELATIONSHIP    VARCHAR(10),
  	PRIMARY KEY (SSN,FNAME)
);

CREATE TABLE ACCOUNT (
    ID      CHAR(10) PRIMARY KEY,
    ATYPE   VARCHAR(8),
    UserName   VARCHAR(32) NOT NULL,
    PASS   VARCHAR(32) NOT NULL,
    SSN     CHAR(9) NOT NULL REFERENCES PERSON(SSN)
		ON DELETE CASCADE
		ON UPDATE CASCADE
);

CREATE TABLE CORDER (
	O_IDX		INT NOT NULL IDENTITY(1,1),
    SSN_CR      CHAR(9) NOT NULL REFERENCES CUSTOMER_RECEIVE(SSN)
		ON DELETE CASCADE
		ON UPDATE CASCADE,
    SSN_CS      CHAR(9) NOT NULL REFERENCES CUSTOMER_SEND(SSN)
		ON DELETE CASCADE
		ON UPDATE CASCADE,
    SSN_EMP     CHAR(9) NOT NULL REFERENCES EMPLOYEE(SSN)
		ON DELETE CASCADE
		ON UPDATE CASCADE,
    ORDERID 	CHAR(10) NOT NULL,
    --TotalPrice      MONEY,
    RATE        TINYINT,
    PaymentType    TEXT,
    --OTIME        DATETIME,
	STATUS		VARCHAR(10),
	OTIME		CHAR(10),
    PRIMARY KEY (ORDERID)
);

CREATE TABLE PACKAGE (
	P_IDX INT NOT NULL IDENTITY(1,1),
    PID CHAR(9) NOT NULL,
    PWEIGHT FLOAT(3),
    TypeName  VARCHAR(7),
    TypeLevel  TINYINT,
    ORDERID CHAR(10) NOT NULL REFERENCES CORDER(ORDERID)
		ON DELETE CASCADE
		ON UPDATE CASCADE,
    SSN     CHAR(9) NOT NULL REFERENCES DRIVER(SSN)
		ON DELETE CASCADE
		ON UPDATE CASCADE,
    --TIME   DATETIME,
	TIME	CHAR(10),
    LOCATION   VARCHAR(64),
    PRIMARY KEY (PID)
);

CREATE TABLE PRICE_RATIO (
	SERVICE_CUSTOMER VARCHAR(8) PRIMARY KEY,
	RATIO REAL
);

CREATE TABLE KILOMETER_DISTANCE (
	PROVINCE VARCHAR(32) PRIMARY KEY,
	DISTANCE INT
);

CREATE TABLE SALARY_BILL (
	EXP TINYINT PRIMARY KEY,
	SALARY BIGINT
);