CREATE or alter PROC NUMPHONE_ACCOUNT 
@type VARCHAR(8), @num_phone TINYINT
AS
BEGIN
	DROP TABLE IF EXISTS ACC_PHONE;
	SELECT ID, COUNT(PHONE) AS NUM_PHONE INTO ACC_PHONE FROM ACCOUNT, PERSON_PHONE
	WHERE ACCOUNT.SSN = PERSON_PHONE.SSN AND ACCOUNT.ATYPE = @type
	GROUP BY ID
	HAVING COUNT(PHONE) = @num_phone
	ORDER BY ID;

	SELECT ACCOUNT.ID, UserName, SSN, ATYPE, NUM_PHONE FROM ACC_PHONE, ACCOUNT
	WHERE ACC_PHONE.ID = ACCOUNT.ID
	ORDER BY ACCOUNT.ID;
END
GO

EXEC NUMPHONE_ACCOUNT 'EMPLOYEE', 3
EXEC NUMPHONE_ACCOUNT 'EMPLOYER', 1
EXEC NUMPHONE_ACCOUNT 'CUSTOMER', 2

-------------------------------------
CREATE or alter PROC LIST_ABOUT_SERVICE 
@service VARCHAR(8)
AS
BEGIN
	DROP TABLE IF EXISTS LINKAGE
	SELECT * INTO LINKAGE FROM (CUSTOMER_SEND JOIN CORDER ON CUSTOMER_SEND.SSN = CORDER.SSN_CS);

	SELECT TEMP.SSN_CS AS SSN,TEMP.ORDERID,COUNT(PACKAGE.PID) AS nPACKAGE,SUM(PACKAGE.PWEIGHT) AS tWEIGHT 
	FROM 
		((SELECT * FROM LINKAGE WHERE LINKAGE.SERVICE = @service) AS TEMP
		JOIN PACKAGE ON TEMP.ORDERID = PACKAGE.ORDERID)
	GROUP BY TEMP.SSN_CS ,TEMP.ORDERID
	HAVING COUNT(PACKAGE.PID) >= 2
	ORDER BY TEMP.ORDERID
END

EXEC LIST_ABOUT_SERVICE 'NORMAL'
EXEC LIST_ABOUT_SERVICE 'FREE'

--SELECT * FROM CUSTOMER_SEND
